config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :genres
  resources :books
  resources :cart, only: %i[create destroy index]
  root 'books#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  # has_many :orders, through: :books_orders_order_id
  has_and_belongs_to_many :books_orders
  accepts_nested_attributes_for :books_orders

  validates :name, presence: true
  validates_uniqueness_of :name
  validates :price, :pages, numericality: true
end

app/models/books_order.rb
class BooksOrder < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :province
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  # has_and_belongs_to_many :books
  belongs_to :order_state
  belongs_to :customer
  # has_many :books, through: :books_orders_book_id
  has_and_belongs_to_many :books_orders

  accepts_nested_attributes_for :books_orders
end

app/models/order_state.rb
class OrderState < ApplicationRecord
  has_many :orders
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session
  before_action :cart
  before_action :user

  helper_method :cart

  add_breadcrumb 'Home', :root_path

  def initialize_session
    session[:cart] ||= []
    session[:user] ||= []
  end

  def cart
    Book.find(session[:cart])
  end

  def user
    Customer.find(session[:user])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = Book.all.includes(:author, :genre)
    @q = @books.ransack(params[:q])
    @search = @q.result.order(:new).page(params[:page]).per(20)

    @genres = Genre.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])

    add_breadcrumb @book.genre.name, @book.genre
    add_breadcrumb @book.name, :book_path
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.fetch(:book, {})
  end

  def get_book_path
    Book.find(params[:id]).name
  end

  def get_genre_path
    Book.find(params[:id]).genre
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  helper_method :get_book
  helper_method :increase_quantity

  def create
    id = params[:id].to_i
    session[:cart] << id
    # logger.debug(session[:cart])
    redirect_to request.referrer
  end

  def index
    add_breadcrumb 'Cart', :cart_index_path
    @cart = session[:cart]
    @items = Book.find(@cart).uniq

    # new_order = Order.create(order_state: OrderState.find(1),
    #                          customer: Customer.find(1),
    #                          pst: 0,
    #                          gst: 0,
    #                          hst: 0)

    # @cart.each do |book_id|
    #   quantity = @cart.count(book_id)
    #   add_book = Book.find(book_id)
    #   BooksOrder.create(book: add_book, order: new_order, price: add_book.price, quantity: quantity)
    # end

    # @book_orders = BooksOrder.where(book_id: @cart, order_id: new_order.id)
  end

  def destroy
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to request.referrer
  end

  def get_book(id)
    Book.find(id)
  end

  def increase_quantity(id)
    @cart = session[:cart]
    session[:cart] << id
    redirect_to request.referrer
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
    @current_genre = Genre.find(params[:id])
    @books = @current_genre.books

    add_breadcrumb @current_genre.name, :genre_path
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit; end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_params
    params.fetch(:genre, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/books/_details.html.erb
<div class="mv-cover-img-large">
  <% if book.image != '' %>
    <%= image_tag book.image, :class => 'img-fluid' %>
  <% else %>
    <%= image_tag ("/images/no_cover.jpg"), :class => 'img-fluid' %>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class='row h-100'>
  <div class='col-sm-3 bg-light  py-4'>
    <%= search_form_for @q do |f|  %>
      <h6>Name</h6>
      <div class="input-group mb-3">
        <%= f.search_field :name_cont, class:'form-control'%>
        <%= f.submit class: 'btn btn-info' %>
      </div>
      <h6>Categories</h6>
      <% @genres.each do |genre|%>
        <div class="input-group mb-3">
          <%= link_to genre.name, genre_path(genre.id)%>
        </div>
      <%end%>
    <% end %>
  </div>
  <div class='col-sm-9  py-4'>
    <div class='row d-flex flex-row justify-content-center align-items-center km-custom-nav'>
      <%= paginate @search%>
    </div>
    <div class="row row-cols-5 g-4 py-4 mb-4">
      <% @search.each do |book| %>
        <%= render partial: "partials/book", locals: {book: book}   %>
      <%end%>
    </div>
    <div class='row d-flex flex-row justify-content-center align-items-center km-custom-nav'>
      <%= paginate @search%>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class='row h-100 pt-4'>
  <div class='col-3'>
    <%= render partial:'partials/cover-large', locals:{book:@book}%>
    <div class='d-flex justify-content-center pt-4'>
      <%= link_to 'Edit', edit_admin_book_path(@book), class: "btn btn-light btn-sm me-2" %>
      <%= link_to 'Back', books_path, class: "btn btn-primary btn-sm"%>
    </div>
  </div>
  <div class="col-8">
    <div class='d-flex flex-row flex-nowrap'>
      <% if !@book.genre.nil? then%><span class="badge rounded-pill bg-primary me-2"><%= @book.genre.name %></span><%end%>
      <% if @book.new then %><span class="badge rounded-pill bg-warning">NEW</span><%end%>
    </div>
    <h2 ><%= @book.name %></h2>
    <h6 ><strong>Price: </strong><%= @book.price %></h6>
    <h6 ><strong>Pages: </strong><%= @book.pages %></h6>
    <p><strong>Description: </strong><br/>
      <%= @book.description %>
    </p>
    <div class='d-flex justify-flex-start mb-3'>
      <%= form_with url: cart_index_path do%>
        <%= hidden_field_tag(:id, @book.id) %>
        <%= button_tag "$ #{@book.price}", class:"btn btn-primary" %>
      <%end%>
    </div>
  </div>
</div>

app/views/cart/index.html.erb
<div class='row h-100'>
  <div class='col-sm-8 py-4'>
    <h5>Order details</h5>
    <% @book_orders.each do |t|%>
      <%=t.book_id%>
    <%end %>
    <table class="table table-striped">
      <thead class='table-dark'>
        <tr>
          <th>Book name</th>
          <th class='col-2'>Quantity</th>
          <th class='col-2'>Price</th>
          <th class='col-1'>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |book|%>
          <% book_quantity = @cart.count(book.id) %>
          <tr>
            <td><%= link_to book.name, book%></td>
            <td>
              <%= form_with do |f| %>
                <div class="input-group">
                  <%# <%= button_to '-', increase_quantity(book.id), class:"btn btn-outline-secondary btn-sm"%>
                  <%= button_tag "-", class:"btn btn-outline-secondary btn-sm", name: 'reduce'%>
                  <%= f.text_field :title, value: book_quantity, class: 'form-control' %>
                  <%= button_tag "+", class:"btn btn-outline-secondary btn-sm", name: 'increment' %>
                </div>
              <%end%>
            </td>
            <td>
              <%= "$ #{(book.price * book_quantity)}"%>
            </td>
            <td>
              <%= form_with url: cart_path(book.id), method: :delete do%>
                <%= button_tag "X", class:"btn btn-danger btn-sm" %>
              <%end%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <div class='col-sm-3 bg-light  py-4'>
    <h5>User details</h5>
  </div>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<div class='genre-img'>
  <%= image_tag @current_genre.image, class:'img-fluid' %>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-10 mx-auto  py-4 px-3 mv-bg-white '>
      <h2 class='mb-4 text-primary'><%= @current_genre.name%></h2>
      <div class="row row-cols-5 g-4 py-4 mb-4">
        <%  @books.each do |book| %>
          <%= render partial:'partials/book', locals:{book: book}%>
        <%end%>
      </div>
    </div>
  </div>
</div>
<%# <%= link_to 'Edit', edit_genre_path(@genre) %>
<%# <%= link_to 'Back', genres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='h-100'>
  <head>
    <title>Base</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class='h-100'>
    <nav class="navbar navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand text-light" href='/'>Minerva</a>
        <div class="d-flex ">
          <%# <a class="btn btn-outline-warning me-2" href='/characters'><strong>Characters</strong></a>
          <a class="btn btn-outline-warning me-2" href='/planets'><strong>Planets</strong></a>
          <a class="btn btn-outline-warning me-2" href='/races'><strong>Species</strong></a> %>
          <%# <%= show_svg('shopping-bag.svg') %>
          <a class="btn btn-light me-2" href="/cart"><strong>Cart</strong>
            <% if session[:cart].size > 0 %>
              <span class="badge bg-danger"> <%= session[:cart].size %></span></a>
          <%end%>
          <a class="btn btn-outline-info" href='/about'>About</a>
        </div>
      </div>
    </nav>
    <div class='container-fluid bg-dark'>
      <div class='container p-1 mv-breadcrumbs'>
        <%= render_breadcrumbs :separator => ' / ' %>
      </div>
    </div>
    <%# <div class='container-fluid bg-danger'>
      <div class='container p-1 mv-breadcrumbs'>
        <%= debug session[:cart] %>
    <%# </div> %>
    <%# </div> %>
    <div class='container p-0 h-100'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_book.html.erb
<div class="col mt-0 mb-4">
  <div class="card" >
    <a href="<%= book_path(book) %>" class="link-dark">
      <div class="mv-cover-img">
        <% if book.image != '' %>
          <%= image_tag book.image, :class => 'img-fluid' %>
        <% else %>
          <%= image_tag ("/images/no_cover.jpg"), :class => 'img-fluid' %>
        <% end %>
      </a>
    </div>
    <div class="card-body">
      <% if !book.genre.nil? then%><span class="badge rounded-pill bg-primary"><%= book.genre.name %></span><%end%>
      <a href="<%= book_path(book) %>" class="link-dark">
        <h5 class="card-title"><%= book.name %></h5>
      </a>
    </div>
    <div class='d-flex justify-content-center mb-3'>
      <%= form_with url: cart_index_path do%>
        <%= hidden_field_tag(:id, book.id) %>
        <%= button_tag "$ #{book.price}", class:"btn btn-primary" %>
      <%end%>
    </div>
  </div>
</div>

app/views/partials/_cover-large.html.erb
<div class="mv-cover-img-large">
  <% if book.image != '' %>
    <%= image_tag book.image, :class => 'img-fluid' %>
  <% else %>
    <%= image_tag ("/images/no_cover.jpg"), :class => 'img-fluid' %>
  <% end %>
</div>

app/views/partials/_cover.html.erb
<div class="col mt-0 mb-4">
  <a href="<%= book_path(book) %>" class="link-dark">
    <div class="card" >
      <div class="mv-cover-img">
        <% if book.image != '' %>
          <%= image_tag book.image, :class => 'img-fluid' %>
        <% else %>
          <%= image_tag ("/images/no_cover.jpg"), :class => 'img-fluid' %>
        <% end %>
      </div>
      <div class="card-body">
        <div class='d-flex flex-row flex-nowrap'>
          <% if !@book.genre.nil? then%><span class="badge rounded-pill bg-primary me-2"><%= @book.genre.name %></span><%end%>
          <% if @book.new then %><span class="badge rounded-pill bg-warning">NEW</span><%end%>
        </div>
        <h5 class="card-title"><%= book.name %></h5>
      </div>
    </div>
  </a>
</div>